# Generated by Django 5.2.14 on 2026-08-01 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0010_site_daily_generation_target_kwh'),
        ('users', '0002_user_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='sites.site'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('INSTALLER', 'Installer'), ('CUSTOMER', 'Customer'), ('SITE_USER', 'Site User')], max_length=20),
        ),
    ]
