# Generated by Django 5.2.14 on 2026-08-11 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_site_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='E.164 format incl. country code, e.g. +91(number). Null = no WhatsApp delivery (opt-out).', max_length=20, null=True),
        ),
    ]
