# Generated by Django 5.2.14 on 2026-08-11 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_whatsapp_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text="WhatsApp number with country code, no '+', e.g. 918424882274. Null = no WhatsApp delivery.", max_length=15, null=True),
        ),
    ]
