# Generated by Django 5.2.14 on 2026-10-02 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0015_device_energy_today_source'),
        ('users', '0005_alter_user_whatsapp_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sites',
            field=models.ManyToManyField(blank=True, related_name='site_users', to='sites.site'),
        ),
    ]
