# Generated by Django 5.2.14 on 2026-10-02 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0015_device_energy_today_source'),
        ('users', '0007_copy_site_to_sites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sites',
            field=models.ManyToManyField(blank=True, limit_choices_to={'site_type': 'GENERATION'}, related_name='site_users', to='sites.site'),
        ),
    ]
