# Generated by Django 5.2.14 on 2026-10-10 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_sites'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='10-digit mobile number the user can log in with instead of email. Leave empty for email-only login.', max_length=10, null=True, unique=True),
        ),
    ]
