# Generated by Django 5.2.14 on 2026-06-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='influx_bucket',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='influx_client_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
