# Generated by Django 5.2.14 on 2026-06-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_customer_influx_bucket_customer_influx_client_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='site_type',
            field=models.CharField(choices=[('GENERATION', 'Generation Plant'), ('SUBSTATION', 'Substation / GSS'), ('OTHER', 'Other')], default='GENERATION', max_length=20),
        ),
    ]
