# Generated by Django 5.2.14 on 2026-06-17 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_site_site_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='influx_device_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='site',
            name='influx_site_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(fields=('site', 'influx_device_id'), name='unique_device_id_per_site'),
        ),
        migrations.AddConstraint(
            model_name='site',
            constraint=models.UniqueConstraint(fields=('customer', 'influx_site_id'), name='unique_site_id_per_customer'),
        ),
    ]
