# Generated by Django 5.2.14 on 2026-06-19 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_alter_device_influx_device_id_and_more'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='installer',
        ),
        migrations.AddField(
            model_name='site',
            name='installer',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='sites', to='tenants.installer'),
            preserve_default=False,
        ),
    ]
