# Generated by Django 5.2.14 on 2026-06-19 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0005_remove_customer_installer_site_installer'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='parent_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_sites', to='sites.site'),
        ),
    ]
