# Generated by Django 5.2.14 on 2026-06-20 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0006_site_parent_site'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='site',
            constraint=models.UniqueConstraint(condition=models.Q(('parent_site__isnull', False)), fields=('parent_site',), name='unique_substation_per_parent_site'),
        ),
    ]
