# Generated by Django 5.2.14 on 2026-07-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0007_site_unique_substation_per_parent_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='ac_capacity_kw',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='dc_capacity_kw',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
