# Generated by Django 5.2.14 on 2026-07-13 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0008_site_ac_capacity_kw_site_dc_capacity_kw'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='energy_offset_kwh',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Manual correction added to raw meter lifetime energy reading ', max_digits=12),
        ),
    ]
