# Generated by Django 5.2.14 on 2026-07-18 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0009_device_energy_offset_kwh'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='daily_generation_target_kwh',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Target daily energy generation for this site, used for performance zone comparisons', max_digits=10, null=True),
        ),
    ]
