# Generated by Django 5.2.14 on 2026-08-31 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0010_site_daily_generation_target_kwh'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='target_cuf_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Target CUF (%) for this site, used for performance zone comparisons', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('INVERTER', 'Inverter'), ('METER', 'Meter'), ('DIDO', 'DIDO'), ('WEATHER_STATION', 'Weather Station'), ('TRANSFORMER', 'Transformer'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
