# Generated by Django 5.2.14 on 2026-09-09 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0011_site_target_cuf_pct_alter_device_device_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='influx_bucket',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
