# Generated by Django 5.2.14 on 2026-09-10 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0012_alter_customer_influx_bucket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('INVERTER', 'Inverter'), ('METER', 'Meter'), ('DIDO', 'DIDO'), ('WEATHER_STATION', 'Weather Station'), ('TRANSFORMER', 'Transformer'), ('ANNUNCIATOR', 'Annunciator'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
