# Generated by Django 5.2.14 on 2026-09-18 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0013_alter_device_device_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='reference_meter',
            field=models.ForeignKey(blank=True, help_text="Meter whose history drives this plant's power/energy figures (active power, energy today, etotal). Defaults to the site's own active 'meter1' when unset. May live on a parent/substation site for a plant with a damaged local meter. If the chosen meter is deactivated, this plant reports no reference meter until a new one is set.", limit_choices_to={'device_type': 'METER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referenced_by_sites', to='sites.device'),
        ),
    ]
