# Generated by Django 5.2.14 on 2026-09-25 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0014_site_reference_meter'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='energy_today_source',
            field=models.CharField(choices=[('COUNTER', 'Counter (energy_total_kwh last / first)'), ('REGISTER', 'Register (energy_today_kw)')], default='COUNTER', help_text="Inverters only. How today's energy is read: COUNTER derives it from the lifetime counter since IST midnight; REGISTER reads the inverter's own energy_today_kw. Switch back to COUNTER if the register misbehaves.", max_length=10),
        ),
    ]
