# Generated by Django 5.2.14 on 2026-10-07 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0015_device_energy_today_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='category',
            field=models.CharField(choices=[('UTILITY', 'Utility'), ('HOUSEHOLD', 'Household')], default='UTILITY', help_text='What kind of plant this is. UTILITY = meter-based plant (meter, inverters, weather station). HOUSEHOLD = inverter-only rooftop site, power and energy come from the inverters.', max_length=20),
        ),
    ]
