# Generated by Django 5.2.14 on 2026-07-14 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0009_device_energy_offset_kwh'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySiteSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('energy_today_kwh', models.DecimalField(decimal_places=3, max_digits=10)),
                ('energy_today_inverter_sum_kwh', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('performance_ratio_pct', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('cuf_pct', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('poa_irradiation_kwh_m2', models.DecimalField(decimal_places=4, max_digits=8, null=True)),
                ('co2_avoided_kg', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('peak_power_kw', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('peak_power_time', models.DateTimeField(null=True)),
                ('meter_status', models.CharField(choices=[('ok', 'OK'), ('no_data', 'No Data')], default='ok', max_length=10)),
                ('inverters_online_count', models.PositiveIntegerField(null=True)),
                ('inverters_total_count', models.PositiveIntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_snapshots', to='sites.site')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('site', 'date')},
            },
        ),
    ]
