# Generated by Django 5.2.14 on 2026-07-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysitesnapshot',
            name='energy_today_kwh',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='dailysitesnapshot',
            name='performance_ratio_pct',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
