# Generated by Django 5.2.14 on 2026-07-31 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_dailysitesnapshot_energy_today_kwh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysitesnapshot',
            name='generation_end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='dailysitesnapshot',
            name='generation_start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
