# Generated by Django 5.2.14 on 2026-08-20 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_dailysitesnapshot_generation_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysitesnapshot',
            name='energy_active_export_kwh',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='End-of-day raw meter export counter (odometer). Cumulative lifetime, NOT offset-corrected. NULL when the meter reported nothing that day. Basis for month-to-date via Postgres last and first.', max_digits=16, null=True),
        ),
    ]
