# Generated by Django 5.2.14 on 2026-08-21 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_dailysitesnapshot_energy_active_export_kwh'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysitesnapshot',
            name='energy_active_export_open_kwh',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Day-start raw meter export counter (odometer at 00:00). Cumulative lifetime, NOT offset-corrected. NULL when the meter reported nothing. Pairs with energy_active_export_kwh (day-end); close / open == energy_today_kwh on a clean day. Independent second source for validating the daily figure.', max_digits=16, null=True),
        ),
    ]
